/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ageofpirates;

import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Jasson
 */
public class BoardSell extends javax.swing.JFrame {
    Player player;
    threadLabel labelThread;
    public JLabel fondo;
    /**
     * Creates new form BoardSell
     */
    public BoardSell(Player player) {
        initComponents();
        this.fondo=new JLabel(new ImageIcon(getClass().getResource("market.jpg")));
        this.player=player;
        this.panelBoardSell.add(fondo);
        fondo.setBounds(0,0,759,513);
        labelThread=new threadLabel();
        labelThread.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBoardSell = new javax.swing.JPanel();
        txfIronToSell = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSell = new javax.swing.JButton();
        lblIron = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSellCanyon = new javax.swing.JButton();
        btnSellMultipleCanyon = new javax.swing.JButton();
        btnSellRedBeardCanyon = new javax.swing.JButton();
        btnSellBombCanyon = new javax.swing.JButton();
        lblSellCanyon = new javax.swing.JLabel();
        lblSellMultipleCanyon = new javax.swing.JLabel();
        lblSellRedBeardCanyon = new javax.swing.JLabel();
        lblSellBombCanyon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txfIronToSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfIronToSellActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hierro a vender: ");

        btnSell.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSell.setText("Vender");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        lblIron.setForeground(new java.awt.Color(255, 255, 255));
        lblIron.setText("jLabel2");

        lblMoney.setForeground(new java.awt.Color(255, 255, 255));
        lblMoney.setText("jLabel3");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1 de hierro=2 $");

        btnSellCanyon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSellCanyon.setText("Vender");
        btnSellCanyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellCanyonActionPerformed(evt);
            }
        });

        btnSellMultipleCanyon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSellMultipleCanyon.setText("Vender");
        btnSellMultipleCanyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellMultipleCanyonActionPerformed(evt);
            }
        });

        btnSellRedBeardCanyon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSellRedBeardCanyon.setText("Vender");
        btnSellRedBeardCanyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellRedBeardCanyonActionPerformed(evt);
            }
        });

        btnSellBombCanyon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSellBombCanyon.setText("Vender");
        btnSellBombCanyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellBombCanyonActionPerformed(evt);
            }
        });

        lblSellCanyon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSellCanyon.setForeground(new java.awt.Color(255, 255, 255));
        lblSellCanyon.setText("Vender un cañon a 500$");

        lblSellMultipleCanyon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSellMultipleCanyon.setForeground(new java.awt.Color(255, 255, 255));
        lblSellMultipleCanyon.setText("Vender un cañon Multiple a 1000$");

        lblSellRedBeardCanyon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSellRedBeardCanyon.setForeground(new java.awt.Color(255, 255, 255));
        lblSellRedBeardCanyon.setText("Vender un cañon Barba roja a 5000$");

        lblSellBombCanyon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSellBombCanyon.setForeground(new java.awt.Color(255, 255, 255));
        lblSellBombCanyon.setText("Vender un cañon bomba a 2000$");

        javax.swing.GroupLayout panelBoardSellLayout = new javax.swing.GroupLayout(panelBoardSell);
        panelBoardSell.setLayout(panelBoardSellLayout);
        panelBoardSellLayout.setHorizontalGroup(
            panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoardSellLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBoardSellLayout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addComponent(lblIron, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279))
                    .addGroup(panelBoardSellLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfIronToSell)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSellRedBeardCanyon)
                            .addGroup(panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSellCanyon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSellMultipleCanyon))
                            .addComponent(lblSellBombCanyon, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(38, 38, 38)
                        .addGroup(panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSellCanyon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSellMultipleCanyon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSellRedBeardCanyon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSellBombCanyon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        panelBoardSellLayout.setVerticalGroup(
            panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoardSellLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfIronToSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSellCanyon)
                    .addComponent(lblSellCanyon))
                .addGap(18, 18, 18)
                .addGroup(panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSell)
                    .addComponent(btnSellMultipleCanyon)
                    .addComponent(lblSellMultipleCanyon))
                .addGap(18, 18, 18)
                .addGroup(panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSellRedBeardCanyon)
                    .addComponent(lblSellRedBeardCanyon))
                .addGap(18, 18, 18)
                .addGroup(panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSellBombCanyon)
                    .addComponent(lblSellBombCanyon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(panelBoardSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIron)
                    .addComponent(lblMoney))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBoardSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBoardSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfIronToSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfIronToSellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfIronToSellActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:
        int hierro = Integer.valueOf(txfIronToSell.getText());
        if(hierro<=player.getIron()){
            player.setIron(player.getIron()-hierro);
            player.setMoney(player.getMoney()+(hierro*2));
        }
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnSellCanyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellCanyonActionPerformed

        if(player.getGroup()[0].size()>0){
            player.getGroup()[0].remove(0);
            player.setMoney(player.getMoney()+500);
        }
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnSellCanyonActionPerformed

    private void btnSellMultipleCanyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellMultipleCanyonActionPerformed
        if(player.getGroup()[1].size()>0){
            player.getGroup()[1].remove(0);
            player.setMoney(player.getMoney()+1000);
        }
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnSellMultipleCanyonActionPerformed

    private void btnSellRedBeardCanyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellRedBeardCanyonActionPerformed
        if(player.getGroup()[2].size()>0){
            player.getGroup()[2].remove(0);
            player.setMoney(player.getMoney()+5000);
        }
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnSellRedBeardCanyonActionPerformed

    private void btnSellBombCanyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellBombCanyonActionPerformed
        if(player.getGroup()[3].size()>0){
            player.getGroup()[3].remove(0);
            player.setMoney(player.getMoney()+2000);
        }
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnSellBombCanyonActionPerformed
    public class threadLabel extends Thread{
    public boolean isRunning = true, isPaused=false;
    public void setIsPaused(boolean isPaused) {
        this.isPaused = isPaused;
    }
    public void run(){ 
        while(isRunning){
            try {
                lblMoney.setText("Total de Dinero: "+player.getMoney());
                lblIron.setText("Total de Hierro: "+player.getIron());
                while(isPaused){
                    sleep(10);
                }
            }catch (InterruptedException ex) {   
            } 
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnSellBombCanyon;
    private javax.swing.JButton btnSellCanyon;
    private javax.swing.JButton btnSellMultipleCanyon;
    private javax.swing.JButton btnSellRedBeardCanyon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIron;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblSellBombCanyon;
    private javax.swing.JLabel lblSellCanyon;
    private javax.swing.JLabel lblSellMultipleCanyon;
    private javax.swing.JLabel lblSellRedBeardCanyon;
    private javax.swing.JPanel panelBoardSell;
    private javax.swing.JTextField txfIronToSell;
    // End of variables declaration//GEN-END:variables
}
