/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ageofpirates;

import ageofpirates.Factory.Armory;
import ageofpirates.Factory.Conector;
import ageofpirates.Factory.EnergyFount;
import ageofpirates.Factory.Mine;
import ageofpirates.Factory.WitchTemple;
import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jasson
 */
public class Market extends javax.swing.JFrame {
    private Player player;
    public JLabel fondo;
    Sea sea;
    threadLabel labelThread;
    
    /**
     * Creates new form Market
     */
    public Market(Player player,Sea sea) {
        initComponents();
        this.fondo=new JLabel(new ImageIcon(getClass().getResource("20887.jpg")));
        this.player=player;        
        this.panelMarket.add(fondo);
        fondo.setBounds(0,0,759,513);
        this.sea=sea;
        labelThread=new threadLabel();
        labelThread.start();
        //System.out.println(this.getBounds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMarket = new javax.swing.JPanel();
        labelIron = new javax.swing.JLabel();
        labelGold = new javax.swing.JLabel();
        btnGhostShip = new javax.swing.JButton();
        btnConnector = new javax.swing.JButton();
        btnWitchTemple = new javax.swing.JButton();
        btnFountEnergy = new javax.swing.JButton();
        btnRedBeard = new javax.swing.JButton();
        btnMine = new javax.swing.JButton();
        btnMerchanCanyon = new javax.swing.JButton();
        btnMerchanBomb = new javax.swing.JButton();
        btnMerchanMultipleCanyon = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        lblMinaNombre = new javax.swing.JLabel();
        lblGhostShipName = new javax.swing.JLabel();
        lblMinaCosto = new javax.swing.JLabel();
        lblGhostShipCost = new javax.swing.JLabel();
        lblConnectorName = new javax.swing.JLabel();
        lblConnectorCost = new javax.swing.JLabel();
        lblWitchName = new javax.swing.JLabel();
        lblWitchCost = new javax.swing.JLabel();
        lblFountName = new javax.swing.JLabel();
        lblFountCost = new javax.swing.JLabel();
        lblMerchanName = new javax.swing.JLabel();
        lblMerchanCost = new javax.swing.JLabel();
        lblMultipleCanyon = new javax.swing.JLabel();
        lblMultipleCanyonCost = new javax.swing.JLabel();
        lblRedBeard = new javax.swing.JLabel();
        lblRedBeardCost = new javax.swing.JLabel();
        lblBomb = new javax.swing.JLabel();
        lblBombCost = new javax.swing.JLabel();
        lblSell = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelIron.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelIron.setText("jLabel1");

        labelGold.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelGold.setText("jLabel2");

        btnGhostShip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/GhostShip.jpg"))); // NOI18N
        btnGhostShip.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/GhostShip.jpg"))); // NOI18N
        btnGhostShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhostShipActionPerformed(evt);
            }
        });

        btnConnector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/conector.png"))); // NOI18N
        btnConnector.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/conector.png"))); // NOI18N
        btnConnector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectorActionPerformed(evt);
            }
        });

        btnWitchTemple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/WitchTemple.png"))); // NOI18N
        btnWitchTemple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWitchTempleActionPerformed(evt);
            }
        });

        btnFountEnergy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/energy.png"))); // NOI18N
        btnFountEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFountEnergyActionPerformed(evt);
            }
        });

        btnRedBeard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/merchan.jpg"))); // NOI18N
        btnRedBeard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedBeardActionPerformed(evt);
            }
        });

        btnMine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/IronMine.png"))); // NOI18N
        btnMine.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/IronMine.png"))); // NOI18N
        btnMine.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/IronMine.png"))); // NOI18N
        btnMine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMineMouseExited(evt);
            }
        });
        btnMine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMineActionPerformed(evt);
            }
        });

        btnMerchanCanyon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/merchan.jpg"))); // NOI18N
        btnMerchanCanyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMerchanCanyonActionPerformed(evt);
            }
        });

        btnMerchanBomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/merchan.jpg"))); // NOI18N
        btnMerchanBomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMerchanBombActionPerformed(evt);
            }
        });

        btnMerchanMultipleCanyon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/merchan.jpg"))); // NOI18N
        btnMerchanMultipleCanyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMerchanMultipleCanyonActionPerformed(evt);
            }
        });

        btnSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageofpirates/Sell.jpg"))); // NOI18N
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        lblMinaNombre.setBackground(new java.awt.Color(0, 0, 0));
        lblMinaNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMinaNombre.setForeground(new java.awt.Color(242, 242, 242));
        lblMinaNombre.setText("Mina de Hierro");
        lblMinaNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblGhostShipName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGhostShipName.setForeground(new java.awt.Color(255, 255, 255));
        lblGhostShipName.setText("Barco Fantasma");
        lblGhostShipName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblMinaCosto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMinaCosto.setText("Costo: 1000$");

        lblGhostShipCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGhostShipCost.setText("Costo: 2500$");

        lblConnectorName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConnectorName.setForeground(new java.awt.Color(255, 255, 255));
        lblConnectorName.setText("Conector");
        lblConnectorName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblConnectorCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConnectorCost.setText("Costo: 100$");

        lblWitchName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWitchName.setForeground(new java.awt.Color(255, 255, 255));
        lblWitchName.setText("Templo de la bruja");
        lblWitchName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblWitchCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWitchCost.setText("Costo: 2500$");

        lblFountName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFountName.setForeground(new java.awt.Color(255, 255, 255));
        lblFountName.setText("Fuente de energia");
        lblFountName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblFountCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFountCost.setText("Costo: 12000$");

        lblMerchanName.setBackground(new java.awt.Color(255, 255, 255));
        lblMerchanName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMerchanName.setForeground(new java.awt.Color(255, 255, 255));
        lblMerchanName.setText("Armeria de Cañones");
        lblMerchanName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblMerchanCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMerchanCost.setText("Costo: 1500$");

        lblMultipleCanyon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMultipleCanyon.setForeground(new java.awt.Color(255, 255, 255));
        lblMultipleCanyon.setText("Cañon Multiple");
        lblMultipleCanyon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblMultipleCanyonCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMultipleCanyonCost.setText("Costo: 1500$");

        lblRedBeard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRedBeard.setForeground(new java.awt.Color(255, 255, 255));
        lblRedBeard.setText("Cañon BarbaRoja");
        lblRedBeard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblRedBeardCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRedBeardCost.setText("Costo: 1500$");

        lblBomb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBomb.setForeground(new java.awt.Color(255, 255, 255));
        lblBomb.setText("Cañon Bomba");
        lblBomb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblBombCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBombCost.setText("Costo: 1500$");

        lblSell.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSell.setText("   Vender");
        lblSell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout panelMarketLayout = new javax.swing.GroupLayout(panelMarket);
        panelMarket.setLayout(panelMarketLayout);
        panelMarketLayout.setHorizontalGroup(
            panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarketLayout.createSequentialGroup()
                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMarketLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnMine, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelMarketLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lblMinaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelMarketLayout.createSequentialGroup()
                                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnMerchanCanyon, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMerchanName))
                                .addGap(5, 5, 5))
                            .addComponent(lblMinaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMarketLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMerchanCost, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMarketLayout.createSequentialGroup()
                        .addComponent(lblMultipleCanyonCost, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBombCost, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(panelMarketLayout.createSequentialGroup()
                        .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMarketLayout.createSequentialGroup()
                                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(panelMarketLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(lblGhostShipCost, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnGhostShip, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGhostShipName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelMarketLayout.createSequentialGroup()
                                        .addComponent(btnMerchanMultipleCanyon, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)))
                                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelMarketLayout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addComponent(lblConnectorCost, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMarketLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnRedBeard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnConnector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMarketLayout.createSequentialGroup()
                                                    .addComponent(lblConnectorName, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(15, 15, 15)))))
                                    .addGroup(panelMarketLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelMarketLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(lblRedBeardCost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblRedBeard))))
                                .addGap(19, 19, 19)
                                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMarketLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblBomb, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnWitchTemple, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblWitchName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblWitchCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMerchanBomb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                            .addComponent(lblMultipleCanyon, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMarketLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFountEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblFountCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFountName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(panelMarketLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMarketLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSell, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMarketLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(labelIron, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelGold, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        panelMarketLayout.setVerticalGroup(
            panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMarketLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFountEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWitchTemple, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConnector, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGhostShip, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMine, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinaNombre)
                    .addComponent(lblGhostShipName)
                    .addComponent(lblConnectorName)
                    .addComponent(lblWitchName)
                    .addComponent(lblFountName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhostShipCost)
                    .addComponent(lblConnectorCost)
                    .addComponent(lblWitchCost)
                    .addComponent(lblFountCost)
                    .addComponent(lblMinaCosto))
                .addGap(30, 30, 30)
                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRedBeard, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMerchanMultipleCanyon, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMerchanCanyon, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMerchanBomb, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMerchanName)
                    .addComponent(lblMultipleCanyon)
                    .addComponent(lblRedBeard)
                    .addComponent(lblBomb)
                    .addComponent(lblSell))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMerchanCost)
                    .addComponent(lblMultipleCanyonCost)
                    .addComponent(lblRedBeardCost)
                    .addComponent(lblBombCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(panelMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIron, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMarket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMarket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMineMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMineMouseEntered

    private void btnMineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMineMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMineMouseExited

    private void btnMineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMineActionPerformed
        if(player.getMoney()>=1000){
            sea.objective= new Mine(player);
            JOptionPane.showMessageDialog(null, "coloca la mina donde desee");
            sea.colocacion=true;
            player.setMoney(player.getMoney()-sea.objective.getCost());
        }else
            JOptionPane.showMessageDialog(null, "No tienes dinero suficiente");     
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnMineActionPerformed

    private void btnGhostShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhostShipActionPerformed
        if(player.getMoney()>=2500){
            String enemyName=JOptionPane.showInputDialog("Introducir nombre del enemigo:");
            for (int i = 0; i < sea.enemiesFactories.size() ; i++) {
                if(enemyName.equals(sea.nameList.get(i))){
                    sea.boardEnemy.get(i).setVisible(true);
                    sea.boardEnemy.get(i).ghost=true;
                    player.setMoney(player.getMoney()-2500);
                }
            }
            //despues de saber el nombre del enemigo, abre la ventana de ese enemigo, que selecione una casilla
            //luego reciba el i y j, saque un random entre 4 y 8 y despues si hay algo le pone la foto de ello.
            
        }else
            JOptionPane.showMessageDialog(null, "No tienes dinero suficiente");
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnGhostShipActionPerformed

    private void btnConnectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectorActionPerformed
        if(player.getMoney()>=100){
            sea.objective= new Conector();
            JOptionPane.showMessageDialog(null, "coloca el conector donde desees");
            sea.colocacion=true;
            player.setMoney(player.getMoney()-sea.objective.getCost());
        }else
            JOptionPane.showMessageDialog(null, "No tienes dinero suficiente");
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnConnectorActionPerformed

    private void btnWitchTempleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWitchTempleActionPerformed
        if(player.getMoney()>=2500){
            sea.objective= new WitchTemple(sea);
            JOptionPane.showMessageDialog(null, "coloca el templo donde desees");
            sea.colocacion=true;
            player.setMoney(player.getMoney()-sea.objective.getCost());
        }else
            JOptionPane.showMessageDialog(null, "No tienes dinero suficiente");
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnWitchTempleActionPerformed

    private void btnFountEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFountEnergyActionPerformed
        if(player.getMoney()>=12000){
            sea.objective= new EnergyFount();
            JOptionPane.showMessageDialog(null, "coloca la fuente donde desees");
            sea.colocacion=true;
            player.setMoney(player.getMoney()-sea.objective.getCost());
        }else
            JOptionPane.showMessageDialog(null, "No tienes dinero suficiente");
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnFountEnergyActionPerformed

    private void btnMerchanCanyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMerchanCanyonActionPerformed
        if(player.getMoney()>=1500){
            sea.objective= new Armory(7);
            JOptionPane.showMessageDialog(null, "coloca la armeria de cañones donde desees");
            sea.colocacion=true;
            player.setMoney(player.getMoney()-sea.objective.getCost());
        }else
            JOptionPane.showMessageDialog(null, "No tienes dinero suficiente");
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnMerchanCanyonActionPerformed

    private void btnMerchanMultipleCanyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMerchanMultipleCanyonActionPerformed
        if(player.getMoney()>=1500){
            sea.objective= new Armory(8);
            JOptionPane.showMessageDialog(null, "coloca la armeria de cañones multiples donde desees");
            sea.colocacion=true;
            player.setMoney(player.getMoney()-sea.objective.getCost());
        }else
            JOptionPane.showMessageDialog(null, "No tienes dinero suficiente");
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnMerchanMultipleCanyonActionPerformed

    private void btnRedBeardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedBeardActionPerformed
        if(player.getMoney()>=1500){
            sea.objective= new Armory(9);
            JOptionPane.showMessageDialog(null, "coloca la armeria de cañones barba roja donde desees");
            sea.colocacion=true;
            player.setMoney(player.getMoney()-sea.objective.getCost());
        }else
            JOptionPane.showMessageDialog(null, "No tienes dinero suficiente");
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnRedBeardActionPerformed

    private void btnMerchanBombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMerchanBombActionPerformed
        if(player.getMoney()>=1500){
            sea.objective= new Armory(10);
            JOptionPane.showMessageDialog(null, "coloca la armería de cañones Bomba donde desees");
            sea.colocacion=true;
            player.setMoney(player.getMoney()-sea.objective.getCost());
        }else
            JOptionPane.showMessageDialog(null, "No tienes dinero suficiente");
        labelThread.isRunning=false;
        this.dispose();
    }//GEN-LAST:event_btnMerchanBombActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:
    String[] options = {"A la tienda.", "A un jugador."}; 
    int result = JOptionPane.showOptionDialog(
       this,
       "Prefieres vender a un jugador o a la tienda?", 
       "Swing Tester",            
       JOptionPane.YES_NO_OPTION,
       JOptionPane.QUESTION_MESSAGE,
       null,     //no custom icon
       options,  //button titles
       options[0] //default button
    );
    switch (result) {
        case JOptionPane.YES_OPTION:
            System.out.println("Le vendista a la tienda");
            BoardSell boardSell=new BoardSell(player);
            boardSell.setVisible(true);
            break;
        case JOptionPane.NO_OPTION:
            System.out.println("Le vendista al jugador");
            
            break;
        default:
            System.out.println("Preferiste no vendérselo a nadie");
            break;
    }
    labelThread.isRunning=false;
    this.dispose();
    }//GEN-LAST:event_btnSellActionPerformed
public class threadLabel extends Thread{
    public boolean isRunning = true, isPaused=false;
    public void setIsPaused(boolean isPaused) {
        this.isPaused = isPaused;
    }
    public void run(){ 
        while(isRunning){
            try {
                labelGold.setText("Total de Dinero: "+player.getMoney());
                labelIron.setText("Total de Hierro: "+player.getIron());
                while(isPaused){
                    sleep(10);
                }
            }catch (InterruptedException ex) {   
            } 
        }
    }
}
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Market().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnector;
    private javax.swing.JButton btnFountEnergy;
    private javax.swing.JButton btnGhostShip;
    private javax.swing.JButton btnMerchanBomb;
    private javax.swing.JButton btnMerchanCanyon;
    private javax.swing.JButton btnMerchanMultipleCanyon;
    private javax.swing.JButton btnMine;
    private javax.swing.JButton btnRedBeard;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnWitchTemple;
    private javax.swing.JLabel labelGold;
    private javax.swing.JLabel labelIron;
    private javax.swing.JLabel lblBomb;
    private javax.swing.JLabel lblBombCost;
    private javax.swing.JLabel lblConnectorCost;
    private javax.swing.JLabel lblConnectorName;
    private javax.swing.JLabel lblFountCost;
    private javax.swing.JLabel lblFountName;
    private javax.swing.JLabel lblGhostShipCost;
    private javax.swing.JLabel lblGhostShipName;
    private javax.swing.JLabel lblMerchanCost;
    private javax.swing.JLabel lblMerchanName;
    private javax.swing.JLabel lblMinaCosto;
    private javax.swing.JLabel lblMinaNombre;
    private javax.swing.JLabel lblMultipleCanyon;
    private javax.swing.JLabel lblMultipleCanyonCost;
    private javax.swing.JLabel lblRedBeard;
    private javax.swing.JLabel lblRedBeardCost;
    private javax.swing.JLabel lblSell;
    private javax.swing.JLabel lblWitchCost;
    private javax.swing.JLabel lblWitchName;
    private javax.swing.JPanel panelMarket;
    // End of variables declaration//GEN-END:variables
}
